std_msgs/Header header
float64 chaser_mean_a
float64[] roe_scaled
float64[] roe_scaled_true
float64[] x
float64[] P
float64[] std_roe

float64[] diff_R_lvlh_true
float64[] diff_V_lvlh_true

float64[] diff_R_lvlh_est
float64[] diff_V_lvlh_est
float64 diff_lvlh

float64[] chaser_true_R
float64[] chaser_true_V
float64[] target_true_R
float64[] target_true_V
float64[] target_est_R
float64[] target_est_V
float64[] measurement
float64[] pre_residual
float64[] post_residual