codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "25...80"

  status:
    target: auto
    threshold: 0.5
    project: yes
    patch: yes
    changes: no

ignore:
  - "**/test/test*.py"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
