image: osrf/ros:lunar-desktop-xenial

before_script:
  ## Setup ROS workspace
  - echo ${CI_PROJECT_DIR}
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - if [ ! -f CMakeLists.txt ]; then catkin_init_workspace; else echo "CMakeList file already there";fi
  - if [ ! -f .rosinstall ]; then wstool init; else echo "rosinstall file already there";fi
  - ln -s ${CI_PROJECT_DIR} .
  - cd ~/catkin_ws/src
  - wstool up
  - git clone https://github.com/catkin/catkin_simple.git
  - cd ~/catkin_ws
  - ls -a

  ## Install dependencies
  - apt-get -qq update
  - apt-get -qq install software-properties-common wget -y
  - apt-get -qq update
  - apt-get -qq install libopencv-dev python-pip -y
  - pip install numpy sgp4 pytest pdoc matplotlib scikit-learn scipy numpy

docs_and_tests:
  script:
    - mkdir ~/public
    - cd ~/catkin_ws
    - catkin_make
    - source ~/catkin_ws/devel/setup.bash
    - pytest ${CI_PROJECT_DIR}/rospace_lib/ -s
    - rostest --text ${CI_PROJECT_DIR}/rospace_plugins/rqt_simtime_plugin/test/simtime_plugin.test
    - rostest --text ${CI_PROJECT_DIR}/rospace_lib/test/testSimTime.test

    - pdoc --html --html-dir ~/docs ${CI_PROJECT_DIR}/rospace_lib/src/rospace_lib
    - pdoc --html --html-dir ~/docs ${CI_PROJECT_DIR}/rospace_plugins/rqt_simtime_plugin/src/rqt_simtime_plugin/
    - pdoc --html --html-dir ~/docs ${CI_PROJECT_DIR}/rospace_nodes/rospace_propagator/src/propagator/
    - cp -r ~/docs ~/public

  artifacts:
    paths:
    - docs/
    - public

