image: python:2.7

before_script:
  - pip install numpy sgp4 pytest pdoc
  - PYTHONPATH="${PYTHONPATH}:${CI_PROJECT_DIR}/nodes/space_vision/src/"
  - export PYTHONPATH

space_vision:
  script:
    - mkdir documentation
    - pdoc --html --html-dir documentation nodes/space_vision/src/
    - pdoc --html --html-dir documentation nodes/space_vision/src/vision_lib
    - cp -r documentation public

  artifacts:
    paths:
    - documentation/
    - public

